import streamlit as st

st.set_page_config(page_title="Documentation", page_icon="📖")
st.title("IRF Plotter Documentation")

st.markdown("""
# How to Use IRF Plotter for MAT Files

This application allows you to visualize Impulse Response Functions (IRFs) generated by Dynare and saved in MATLAB `.mat` files. You can overlay results from multiple MAT files, customize plot styles, and save/load your plot settings.

## 1. Uploading MAT Files
- **Demo Mode:** Use the checkbox to try the app with a sample MAT file.
- **Upload:** Upload one or more MAT files generated by Dynare. The files must contain the `oo_` and `M_` structures.

## 2. Selecting Variables and Shocks
- **Endogenous Variables:** Select which variables to plot from the list of variables common to all uploaded files.
- **Shocks:** Select the shock to visualize. Only shocks present in all files are available.

## 3. Plot Options
- **Layout:** Choose the number of columns for the subplot grid.
- **Axis Labels:** Customize the X and Y axis labels.
- **Periods:** Set the number of periods to display.
- **Per-File Style:** For each MAT file, set the marker, line style, color, and legend label.
- **Legend:** Toggle legend display and choose whether to show it on all panels or only the first.
- **Grid:** Toggle grid display on the plots.
- **Figure Size:** Adjust the width and height of the figure in inches.

## 4. Saving and Loading Plot Options
- **Save Options:** Download your current plot/UI settings as a YAML file for future use.
- **Load Options:** Upload a previously saved YAML file to restore your settings. If the YAML is invalid, an error will be shown.
- **Redraw:** After loading YAML, click the Redraw button to apply the settings.

## 5. Plotting and Downloading
- **Plot:** The right panel displays the IRF plots for the selected variables and shock.
- **Export:** Download the figure in PNG, PDF, EPS, SVG, or PKL format. Optionally include the figure title.
- **IRF Data:** Expand the "Display IRF Data" section to see the raw data for each MAT file.

---

## Tips
- Only variables and shocks present in all uploaded files can be plotted together.
- YAML save/load does not include variable or shock names, only UI and plot settings.
- The app is responsive: on wide screens, settings and plots are shown side-by-side; on narrow screens, they are stacked vertically.

---

For more details, see the [README](./README.md) or contact the developer.
""")
